### PR TITLE
Implementation of Actinides.

### PR DESCRIPTION
**Pull request by lukaswittmann**
## Description
Added actinides support to the Fortran version, following the Torch autodiff DFT-D3 implementation by [FreeSoulIG](https://github.com/FreeSoulIG).

## Changes Made
- Added support for actinides in the Fortran version, based on the changes made in commit [b943853](https://github.com/dftd3/tad-dftd3/commit/b943853bde9ae39854f26defcfaabf08098afe6f)
- Implemented necessary new vdw and c6ab parameters
- Added new tests for the actinides

Crosschecked and validated results from both implementations to ensure accuracy. The test suite successfully completed without any errors.

### CODE REVIEW

**Comment by awvwgk** [comment]
Thanks for sharing. Looks good to me.

**Review by awvwgk — APPROVED** [review]

**Comment by lukaswittmann** [comment]
Fixed the weird build check error of ubuntu-20.04 `../src/dftd3/reference.f90(2436): catastrophic error: Statement too long` by shortening the lines in the reference file.

**Comment by lukaswittmann** [comment]
The build still fails for [build (ubuntu-20.04, meson, debug, intel, 2021.2.0)](https://github.com/dftd3/simple-dftd3/actions/runs/6795039723/job/18481581141?pr=48#logs), even after lines were truncated.

I am clueless as to why this is happening. Does anyone else have any insights into the possible reasons for this occurrence?

**Comment by awvwgk** [comment]
Can't say why the Intel build is failing, there have been issues with the array constructors and number of continuation lines before. It would be mandatory to fix those issues before merging this patch.

**Review by awvwgk — APPROVED** [review]
Looks good to me now

**Pull request merged**
